version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:3.2.0
    ports:
      - "6379:6379"
    networks:
      - nw
  web:
    container_name: web
    build: ./mmp-api
    ports:
      - "3332:3332"
    volumes:
      - ./:/app
    networks:
      - nw
    depends_on:
      - redis
    links:
      - redis
    command: npm run start
  worker:
    container_name: worker
    build: ./mmp-api
    volumes:
      - ./:/app
    networks:
    - nw
    depends_on:
      - web
      - redis
    command: node ./ace kue:listen
networks:
  nw:
    driver: bridge
